config/routes.rb
Rails.application.routes.draw do

  resources :users do
  	resources :hashtags
  end
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  get 'messages', to: 'messages#index'
  post 'messages', to: 'messages#create'

  get 'logout', to: 'sessions#end'

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :hashtag_users
  has_many :users, :through => :hashtag_users  
  has_many :hashtag_messages
  has_many :messages, :through => :hashtag_messages
  validates :value, presence: true
end

app/models/hashtag_message.rb
class HashtagMessage < ApplicationRecord
	belongs_to :hashtag
	belongs_to :message
end

app/models/hashtag_user.rb
class HashtagUser < ApplicationRecord
	belongs_to :hashtag
	belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
	has_many :hashtag_messages
	has_many :hashtags, :through => :hashtag_messages
	validates :author, presence: true
	validates :body, presence: true
	validates :publication_date, presence: true

	require 'twitter'

	def self.get_messages_from_twitter
		tweets = get_tweets
		save_tweets(tweets)
	end

	def self.get_hashtag_messages_from_twitter(hashtag)
		client = get_twitter_client
		tweets = get_tweets_by_hashtag(client, hashtag.value)
		save_hashtag_tweets(hashtag.id, tweets)
	end

	private
	def self.get_twitter_client
		Twitter::REST::Client.new do |config|
	    	config.consumer_key        = ENV['TWITTER_CONSUMER_KEY']
	    	config.consumer_secret     = ENV['TWITTER_CONSUMER_SECRET']
	    	config.access_token        = ENV['ACCESS_TOKEN']
	    	config.access_token_secret = ENV['ACCESS_TOKEN_SECRET']
		end
	end

	def self.get_tweets
  		client = get_twitter_client

		hashtags = Hashtag.all
		tweets = Hash.new

		hashtags.each do |hashtag|
			tweets[hashtag.id] = get_tweets_by_hashtag(client, hashtag.value)
		end

		tweets
  	end

  	def self.get_tweets_by_hashtag(client, hashtag)
  		tweets = client.search("##{hashtag}").take(100)
  		remove_existing(tweets)
  	end

  	def self.remove_existing(tweets)
  		messages = Message.where(twitter_id: tweets.map(&:id))

  		new_tweets = Array.new
  		existing_tweets_ids = messages.map(&:twitter_id)

  		tweets.each do |tweet|
  			unless existing_tweets_ids.include?(tweet.id)
  				new_tweets.push(tweet)
  			end
  		end

  		return new_tweets
  	end

  	def self.save_tweets(messages)
  		messages.each do |hashtag, tweets|
  			save_hashtag_tweets(hashtag, tweets)
		end
  	end

  	def self.save_hashtag_tweets(hashtag_id, tweets)
  		tweets.each do |tweet|	
			message = save_message_from_tweet(tweet)
			save_hashtag_message(hashtag_id, message.id)
		end
  	end

  	def self.save_message_from_tweet(tweet)
  		message = Message.new
		message.twitter_id = tweet.id
		message.author = tweet.user.screen_name
		message.body = tweet.text
		message.publication_date = tweet.created_at

		message.save

		message
  	end

  	def self.save_hashtag_message(hashtag_id, message_id)
  		hashtag_message = HashtagMessage.new
		hashtag_message.hashtag_id = hashtag_id
		hashtag_message.message_id = message_id

		hashtag_message.save
  	end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :hashtag_users
	has_many :hashtags , :through => :hashtag_users
	validates :username, presence: true
	validates :password_digest, presence: true,
						 length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	before_action :authorized
	helper_method :current_user
	helper_method :logged_in?

	def current_user
		User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def authorized
		redirect_to '/' unless logged_in?
	end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
	layout "navbar"

	def index
		@current_user = current_user
	end

	def show
		@current_user = current_user
		@hashtag = @current_user.hashtags.find(params[:id])
	end

	def new
	end

	def create
		@current_user = current_user
		@hashtag_params = hashtag_parameters
		@hashtag = Hashtag.find_by_value(@hashtag_params[:value])

		if @hashtag.nil?
			@hashtag = @current_user.hashtags.create(@hashtag_params)
		else
			@current_user.user_hashtags.create(user_id: session[:user_id], hashtag_id: @hashtag.id)
		end

		Message.get_hashtag_messages_from_twitter(@hashtag)

		redirect_to user_hashtags_path(@current_user)
	end

	def destroy
		@current_user = current_user
		@id = params[:id]
		@user_hashtag = UserHashtag.find_by(user_id: session[:user_id], hashtag_id: @id)

		@user_hashtag.destroy

		@hashtag = Hashtag.find(@id)

		if @hashtag.users.count == 0
			@hashtag.destroy
		end

		redirect_to user_hashtags_path(@current_user)
	end

	private 
	def hashtag_parameters
		params.require(:hashtag).permit(:value, :user_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  skip_before_action :authorized, only: [:new, :create, :welcome]	

  def new
  end

  def create
  	@user = User.find_by_username(params[:username])

  	if @user && @user.authenticate(params[:password])
  		session[:user_id] = @user.id
  		redirect_to user_hashtags_path(@user)
  	else
  		@login_error = true
  		render 'new'
  	end
  end

  def end
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    layout "navbar"
  
    def index
        @current_user = current_user
        @users = User.all
    end

    def show
        @current_user = current_user
        @user = User.find(params[:id])
    end 

    def new
        @current_user = current_user
        @url = users_path
        @method = :post
    end

    def edit
        @current_user = current_user
        @user = User.find(params[:id])
        @url = user_path(@user)
        @method = :put
    end

    def create
        @current_user = current_user
        parameters = user_parameters

        if parameters[:password] == parameters[:password_repeat]
            password_digest = BCrypt::Password.create(parameters[:password])
            User.create(username: parameters[:username], password_digest: password_digest)
            
            redirect_to users_path
        else
            @password_error = true
            render 'new'
        end
    end

    def update
        parameters = user_parameters
        if parameters[:password] == parameters[:password_repeat]
            password_digest = BCrypt::Password.create(parameters[:password])
            @user = User.find(params[:id])
            @user.update!(username: parameters[:username], password_digest: password_digest)

            redirect_to users_path
        else
            @password_error = true
            render 'edit'
        end
    end

    def destroy
        user = User.find(params[:id])
        user.destroy

        redirect_to users_path
    end

    private
    def user_parameters
        params.permit(:username, :password, :password_repeat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hashtags/_form.html.erb
<%= form_with(model: [ @current_user, @current_user.hashtags.build ], class: "form-inline row") do |form| %>
		<div class="col-sm">
	    	<%= form.label :nova_hashtag, class: "float-left" %>
	    </div>
	    <div class="col-sm">
	    	<%= form.text_field :value, placeholder: "Digite a hashtag sem #", class: "form-control" %>
	    </div>
	    <div class="col-sm">
	    	<%= form.submit "Cadastrar Hashtag", class: "btn btn-primary float-right" %>
	    </div>
<% end %>

app/views/hashtags/index.html.erb
<h1>Minhas hastags:</h1>

<br>

<% if @current_user.hashtags.count > 0 %>

<% @current_user.hashtags.each do |hashtag| %>

<div class="row">
	<div class="col-sm"><%= hashtag.value %></div>
	<div class="col-sm">
		<%= link_to 'Exibir tweets', user_hashtag_path(@current_user, hashtag), class: "btn" %>
	</div>
	<div class="col-sm">
		<div class="float-right">
			<%= button_to 'Remover Hashtag', [@current_user, hashtag], 
				method: :delete,
				data: { confirm: 'Você tem certeza?' },
				class: "btn btn-danger" %>
		</div>
	</div>
</div>

<hr>

<% end %>


<% else %>

<p>Não há hashtags cadastradas!</p>

<% end %>

<%= render 'hashtags/form' %>

</div>

app/views/hashtags/show.html.erb
<br>

<h2>Mensagens da Hashtag: <b> #<%= @hashtag.value %> </b></h1>

<br>	

<table class="table">

<tr>
	<th>Usuario</th>
	<th>Mensagem</th>
	<th>Data</th>
</tr>

<% @hashtag.messages.each do |message| %>

<tr>
	<td>@<%= message.author %></td>
	<td><%= message.body %></td>
	<td><%= message.publication_date.to_s(:db) %></td>
</tr>

<% end %>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BirdCatcher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm"></div>      
        <div class="col-sm">
          <%= yield %>
        </div>
        <div class="col-sm"></div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/navbar.html.erb
<!DOCTYPE html>
<html>
	<head>
    	<title>BirdCatcher</title>
    	<%= csrf_meta_tags %>
    	<%= csp_meta_tag %>

    	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  	</head>

	<body>
		<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
			<a class="navbar-brand">Bird Catcher</a>
			<ul class="navbar-nav">
				<li class="nav-item">
					<%= link_to "Hashtags", user_hashtags_path(@current_user), class: "nav-link" %>
				</li>
			</ul>
		  	<ul class="navbar-nav ml-auto">
		  		<li class="nav-item">
		  			<%= link_to "Usuários", users_path, class: "nav-link" %>
		  		</li>
		  		<li class="nav-item">
		  			<%= link_to "Sair", logout_path, class: "nav-link" %>
		  		</li>
		  	</ul>
		</nav>
 		<div class="container-fluid">
	    	<div class="row">
	        	<div class="col-sm-2"></div>      
	        	<div class="col-sm-8">
	          	<%= yield %>
	        	</div>
	        	<div class="col-sm-2"></div>
	      	</div>
    	</div>
	</body>
</html>

app/views/users/_form.html.erb
<% if @password_error %>
	<div class="alert alert-danger" role="alert" id="alert">
		Senhas não coincidem!
	</div>
<% end %>

<%= form_with(model: @user, url: @url, method: @method) do |form| %>

	<div class="form-group">
		<%= form.label :usuario %>
		<%= form.text_field :username, placeholder: "Digite o nome de usuário", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= form.label :senha %>
		<%= form.password_field :password, placeholder: "Digite a senha", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= form.label :confirmar %>
		<%= form.password_field :password_repeat, placeholder: "Confirme a senha", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= form.submit "Confirmar", class: "btn btn-primary col-sm-12" %>
	</div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<h1>Editar usuário</h1>
		<hr>
		<%= render 'form' %>
	</div>
	<div class="col-sm-2"></div>
</div>

app/views/users/index.html.erb
<h1>Usuários</h1>
<hr>

<% @users.each do |user| %>
	<div class="row">
		<div class="col-sm">
			<%= user.username %>
		</div>
		<div class="col-sm">
			<%= button_to 'Excluir', user, 
				method: :delete,
				class: "btn btn-danger float-right",
				data: { confirm: 'Você tem certeza?' } %>
		</div>
	</div>

	<hr>
<% end %>

<%= link_to "Novo usuário", new_user_path, class: "btn btn-primary" %>

app/views/users/new.html.erb
<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<h1>Novo usuário</h1>
		<hr>

		<%= render 'form' %>
	</div>
	<div class="col-sm-2"></div>
</div>